import { t } from "intlayer"

const bookAppointmentContent = {
  key: "book-appointment",
  content: {
    title: t({
      en: "Book Appointment",
      si: "වේලාවක් වෙන් කරන්න",
      ta: "அப்பாயிண்ட்மெண்ட் முன்பதிவு",
      hi: "अपॉइंटमेंट बुक करें",
      fr: "Prendre RDV",
      de: "Termin buchen",
      ar: "حجز موعد",
      ja: "予約する",
      zh: "预约挂号",
      es: "Reservar cita",
    }),
    subtitle: t({
      en: "Schedule your next visit in 4 easy steps",
      si: "පියවර 4කින් පහසුවෙන් ඔබගේ ඉදිරි හමුවීම වෙන්කරවා ගන්න",
      ta: "4 எளிய படிகளில் உங்கள் அடுத்த வருகையைத் திட்டமிடுங்கள்",
      hi: "4 आसान चरणों में अपनी अगली यात्रा का समय निर्धारित करें",
      fr: "Planifiez votre prochaine visite en 4 étapes faciles",
      de: "Planen Sie Ihren nächsten Besuch in 4 einfachen Schritten",
      ar: "جدول زيارتك القادمة في 4 خطوات سهلة",
      ja: "4つの簡単なステップで次回の受診を予約しましょう",
      zh: "只需4个简单步骤即可预约下一次就诊",
      es: "Programe su próxima visita en 4 sencillos pasos",
    }),
    stepDoctor: t({
      en: "Doctor",
      si: "වෛද්‍යවරයා",
      ta: "மருத்துவர்",
      hi: "डॉक्टर",
      fr: "Médecin",
      de: "Arzt",
      ar: "الطبيب",
      ja: "医師",
      zh: "医生",
      es: "Médico",
    }),
    stepSession: t({
      en: "Session",
      si: "සැසිය",
      ta: "அமர்வு",
      hi: "सत्र",
      fr: "Session",
      de: "Sitzung",
      ar: "الجلسة",
      ja: "セッション",
      zh: "就诊时间",
      es: "Sesión",
    }),
    stepDetails: t({
      en: "Details",
      si: "තොරතුරු",
      ta: "விவரங்கள்",
      hi: "विवरण",
      fr: "Détails",
      de: "Details",
      ar: "التفاصيل",
      ja: "詳細",
      zh: "详细信息",
      es: "Detalles",
    }),
    stepConfirm: t({
      en: "Confirm",
      si: "තහවුරු කිරීම",
      ta: "உறுதிப்படுத்தல்",
      hi: "पुष्टि करें",
      fr: "Confirmer",
      de: "Bestätigen",
      ar: "تأكيد",
      ja: "確認",
      zh: "确认",
      es: "Confirmar",
    }),
    searchPlaceholder: t({
      en: "Search doctors by name or specialty...",
      si: "නම හෝ විශේෂීකරණය අනුව වෛද්‍යවරුන් සොයන්න...",
      ta: "பெயர் அல்லது சிறப்பு மூலம் மருத்துவர்களைத் தேடுங்கள்...",
      hi: "नाम या विशेषता द्वारा डॉक्टरों की खोज करें...",
      fr: "Rechercher des médecins par nom ou spécialité...",
      de: "Ärzte nach Name oder Fachrichtung suchen...",
      ar: "ابحث عن الأطباء بالاسم أو التخصص...",
      ja: "名前か専門分野で医師を検索...",
      zh: "按姓名或科室搜索医生...",
      es: "Buscar médicos por nombre o especialidad...",
    }),
    consultationFee: t({
      en: "Consultation Fee",
      si: "උපදේශන ගාස්තුව",
      ta: "ஆலோசனை கட்டணம்",
      hi: "परामर्श शुल्क",
      fr: "Frais de consultation",
      de: "Konsultationsgebühr",
      ar: "رسوم الاستشارة",
      ja: "診察料",
      zh: "诊疗费",
      es: "Tarifa de consulta",
    }),
    availableSessions: t({
      en: "Available Sessions",
      si: "ලබාගත හැකි සැසි",
      ta: "கிடைக்கக்கூடிய அமர்வுகள்",
      hi: "उपलब्ध सत्र",
      fr: "Sessions disponibles",
      de: "Verfügbare Sitzungen",
      ar: "الجلسات المتاحة",
      ja: "選択可能なセッション",
      zh: "可选就诊时间",
      es: "Sesiones disponibles",
    }),
    tokensLeft: t({
      en: "tokens left",
      si: "ටෝකන ඉතිරිව ඇත",
      ta: "டோக்கன்கள் மீதமுள்ளன",
      hi: "टोकन बचे हैं",
      fr: "jetons restants",
      de: "Token übrig",
      ar: "أرقام متبقية",
      ja: "残りのトークン",
      zh: "个剩余号源",
      es: "fichas restantes",
    }),
    detailsNotice: t({
      en: "Please provide any relevant details for the doctor prior to the session.",
      si: "කරුණාකර සැසියට පෙර වෛද්‍යවරයා සඳහා අදාළ තොරතුරු ලබා දෙන්න.",
      ta: "அமர்வுக்கு முன் மருத்துவருக்குத் தேவையான விவரங்களை வழங்கவும்.",
      hi: "कृपया सत्र से पहले डॉक्टर के लिए कोई भी प्रासंगिक विवरण प्रदान करें।",
      fr: "Veuillez fournir tous les détails pertinents pour le médecin avant la session.",
      de: "Bitte geben Sie dem Arzt vor der Sitzung alle relevanten Details an.",
      ar: "يرجى تقديم أي تفاصيل ذات صلة للطبيب قبل الجلسة.",
      ja: "受診前に医師への伝達事項を入力してください。",
      zh: "请在就诊前为医生提供任何相关的详细信息。",
      es: "Por favor, proporcione cualquier detalle relevante para el médico antes de la sesión.",
    }),
    complaintLabel: t({
      en: "Chief Complaint / Reason for visit",
      si: "ප්‍රධාන රෝග ලක්ෂණය / පැමිණීමට හේතුව",
      ta: "முக்கிய புகார் / வருகைக்கான காரணம்",
      hi: "मुख्य शिकायत / आने का कारण",
      fr: "Motif principal de consultation",
      de: "Hauptbeschwerde / Grund des Besuchs",
      ar: "الشكوى الرئيسية / سبب الزيارة",
      ja: "主な症状 / 受診の理由",
      zh: "主诉 / 就诊原因",
      es: "Queja principal / Motivo de la visita",
    }),
    complaintPlaceholder: t({
      en: "E.g., Experiencing mild chest pain for the last 2 days...",
      si: "උදා: පසුගිය දින 2 තිස්සේ පපුවේ සුළු වේදනාවක් පැවතීම...",
      ta: "உதாரணமாக, கடந்த 2 நாட்களாக லேசான நெஞ்சு வலி ஏற்படுகிறது...",
      hi: "जैसे, पिछले 2 दिनों से छाती में हल्का दर्द हो रहा है...",
      fr: "Ex: Légère douleur thoracique depuis 2 jours...",
      de: "Z. B. Leichte Brustschmerzen in den letzten 2 Tagen...",
      ar: "مثال: ألم خفيف في الصدر خلال اليومين الماضيين...",
      ja: "例：ここ2日間、軽い胸の痛みがあります...",
      zh: "例如：最近两天感到轻微胸痛...",
      es: "Ej. Experimentando dolor leve en el pecho durante los últimos 2 días...",
    }),
    bookingConfirmedTitle: t({
      en: "Booking Confirmed!",
      si: "වෙන්කරවා ගැනීම තහවුරුයි!",
      ta: "முன்பதிவு உறுதி செய்யப்பட்டது!",
      hi: "बुकिंग की पुष्टि हो गई!",
      fr: "Réservation confirmée !",
      de: "Buchung bestätigt!",
      ar: "تم تأكيد الحجز!",
      ja: "予約が確定しました！",
      zh: "预约已确认！",
      es: "¡Reserva confirmada!",
    }),
    bookingConfirmedDesc: t({
      en: "Your appointment is confirmed.",
      si: "ඔබගේ වේලාව වෙන් කිරීම සාර්ථකව තහවුරු කර ඇත.",
      ta: "உங்கள் அப்பாயிண்ட்மெண்ட் உறுதி செய்யப்பட்டுள்ளது.",
      hi: "आपकी अपॉइंटमेंट की पुष्टि हो गई है।",
      fr: "Votre rendez-vous est confirmé.",
      de: "Ihr Termin ist bestätigt.",
      ar: "تم تأكيد موعدك.",
      ja: "予約が正常に完了しました。",
      zh: "您的预约已确认。",
      es: "Su cita está confirmada.",
    }),
    tokenNumberLabel: t({
      en: "Your Token Number",
      si: "ඔබගේ ටෝකන් අංකය",
      ta: "உங்கள் டோக்கன் எண்",
      hi: "आपका टोकन नंबर",
      fr: "Votre numéro de jeton",
      de: "Ihre Token-Nummer",
      ar: "رقم دورك",
      ja: "あなたのトークン番号",
      zh: "您的号码",
      es: "Su número de ficha",
    }),
    goToDashboard: t({
      en: "Go to Dashboard",
      si: "පාලක පුවරුව වෙත යන්න",
      ta: "டாஷ்போர்டுக்குச் செல்லவும்",
      hi: "डैशबोर्ड पर जाएं",
      fr: "Aller au tableau de bord",
      de: "Zum Dashboard gehen",
      ar: "الذهاب إلى لوحة التحكم",
      ja: "ダッシュボードへ移動",
      zh: "返回控制台",
      es: "Ir al Panel de control",
    }),
    summaryTitle: t({
      en: "Summary",
      si: "සාරාංශය",
      ta: "சுருக்கம்",
      hi: "सारांश",
      fr: "Résumé",
      de: "Zusammenfassung",
      ar: "الملخص",
      ja: "概要",
      zh: "账单详情",
      es: "Resumen",
    }),
    doctorLabel: t({
      en: "Doctor",
      si: "වෛද්‍යවරයා",
      ta: "மருத்துவர்",
      hi: "डॉक्टर",
      fr: "Médecin",
      de: "Arzt",
      ar: "الطبيب",
      ja: "医師",
      zh: "医生",
      es: "Médico",
    }),
    dateLabel: t({
      en: "Date",
      si: "දිනය",
      ta: "தேதி",
      hi: "तारीख",
      fr: "Date",
      de: "Datum",
      ar: "التاريخ",
      ja: "日付",
      zh: "日期",
      es: "Fecha",
    }),
    timeLabel: t({
      en: "Time",
      si: "වේලාව",
      ta: "நேரம்",
      hi: "समय",
      fr: "Heure",
      de: "Uhrzeit",
      ar: "الوقت",
      ja: "時間",
      zh: "时间",
      es: "Hora",
    }),
    bookingFee: t({
      en: "Booking Fee",
      si: "වෙන්කිරීමේ ගාස්තුව",
      ta: "முன்பதிவு கட்டணம்",
      hi: "बुकिंग शुल्क",
      fr: "Frais de réservation",
      de: "Buchungsgebühr",
      ar: "رسوم الحجز",
      ja: "予約手数料",
      zh: "预约手续费",
      es: "Tarifa de reserva",
    }),
    totalPayable: t({
      en: "Total Payable",
      si: "මුළු ගෙවිය යුතු මුදල",
      ta: "மொத்தம் செலுத்த வேண்டியது",
      hi: "कुल देय",
      fr: "Total à payer",
      de: "Gesamtbetrag",
      ar: "إجمالي المبلغ المستحق",
      ja: "合計支払額",
      zh: "应付总额",
      es: "Total a pagar",
    }),
    payButton: t({
      en: "Pay with PayHere",
      si: "PayHere හරහා ගෙවන්න",
      ta: "PayHere மூலம் செலுத்தவும்",
      hi: "PayHere के साथ भुगतान करें",
      fr: "Payer avec PayHere",
      de: "Mit PayHere bezahlen",
      ar: "الدفع عبر PayHere",
      ja: "PayHereで支払う",
      zh: "使用 PayHere 支付",
      es: "Pagar con PayHere",
    }),
    processingPayment: t({
      en: "Processing Payment...",
      si: "ගෙවීම් ක්‍රියාත්මක වෙමින් පවතී...",
      ta: "கட்டணம் செலுத்தப்படுகிறது...",
      hi: "भुगतान संसाधित हो रहा है...",
      fr: "Traitement du paiement...",
      de: "Zahlung wird verarbeitet...",
      ar: "جاري معالجة الدفع...",
      ja: "決済処理中...",
      zh: "正在处理支付...",
      es: "Procesando pago...",
    }),
    backButton: t({
      en: "Back",
      si: "ආපසු",
      ta: "பின்னால்",
      hi: "पीछे",
      fr: "Retour",
      de: "Zurück",
      ar: "رجوع",
      ja: "戻る",
      zh: "返回",
      es: "Atrás",
    }),
    continueButton: t({
      en: "Continue",
      si: "ඉදිරියට යන්න",
      ta: "தொடரவும்",
      hi: "आगे बढ़ें",
      fr: "Continuer",
      de: "Weiter",
      ar: "استمرار",
      ja: "次へ",
      zh: "继续",
      es: "Continuar",
    }),
  },
}

export default bookAppointmentContent
