import { t, type Dictionary } from "intlayer"

const queueTrackerContent = {
  key: "queue-tracker",
  content: {
    title: t({
      en: "Live Queue Tracker",
      si: "සජීවී පෝලිම් ට්‍රැකර්",
      ta: "நேரடி வரிசை டிராக்கர்",
      hi: "लाइव कतार ट्रैकर",
      fr: "Suivi de file en direct",
      de: "Live-Warteschlangen-Tracker",
      ar: "متبع الطابور المباشر",
      ja: "ライブ待ち順トラッカー",
      zh: "实时排队追踪",
      es: "Seguimiento de cola en vivo",
    }),
    subtitle: t({
      en: "Track your appointment in real-time",
      si: "ඔබගේ හමුවීම සජීවීව නිරීක්ෂණය කරන්න",
      ta: "உங்கள் அப்பாயிண்ட்மெண்ட்டை நிகழ்நேரத்தில் கண்காணிக்கவும்",
      hi: "वास्तविक समय में अपने अपॉइंटमेंट को ट्रैक करें",
      fr: "Suivez votre rendez-vous en temps réel",
      de: "Verfolgen Sie Ihren Termin in Echtzeit",
      ar: "تتبع موعدك في الوقت الحقيقي",
      ja: "予約状況をリアルタイムで確認",
      zh: "实时追踪您的预约进度",
      es: "Siga su cita en tiempo real",
    }),
    sessionActive: t({
      en: "Session In Progress",
      si: "සැසිය ක්‍රියාත්මක වෙමින් පවතී",
      ta: "அமர்வு செயல்பாட்டில் உள்ளது",
      hi: "सत्र प्रगति पर है",
      fr: "Session en cours",
      de: "Sitzung läuft",
      ar: "الجلسة جارية",
      ja: "セッション進行中",
      zh: "就诊进行中",
      es: "Sesión en progreso",
    }),
    sessionInactive: t({
      en: "Session Not Started",
      si: "සැසිය තවමත් ආරම්භ කර නොමැත",
      ta: "அமர்வு தொடங்கவில்லை",
      hi: "सत्र शुरू नहीं हुआ",
      fr: "Session non commencée",
      de: "Sitzung nicht gestartet",
      ar: "لم تبدأ الجلسة بعد",
      ja: "セッション開始前",
      zh: "就诊未开始",
      es: "Sesión no iniciada",
    }),
    currentlyCalling: t({
      en: "Currently Calling",
      si: "දැනට කැඳවන අංකය",
      ta: "தற்போது அழைக்கப்படுகிறது",
      hi: "वर्तमान में बुला रहे हैं",
      fr: "Appel en cours",
      de: "Aktueller Aufruf",
      ar: "يتم استدعاؤه حاليًا",
      ja: "現在お呼び出し中",
      zh: "当前呼叫",
      es: "Llamando actualmente",
    }),
    yourToken: t({
      en: "Your Token",
      si: "ඔබගේ ටෝකන් අංකය",
      ta: "உங்கள் டோக்கன்",
      hi: "आपका टोकन",
      fr: "Votre jeton",
      de: "Ihr Token",
      ar: "رقم دورك",
      ja: "あなたのトークン",
      zh: "您的号码",
      es: "Su ficha",
    }),
    estWait: t({
      en: "Est. Wait",
      si: "ඇස්තමේන්තුගත කාලය",
      ta: "மதிப்பிடப்பட்ட காத்திருப்பு",
      hi: "अनुमानित प्रतीक्षा",
      fr: "Attente est.",
      de: "Geschätzte Wartezeit",
      ar: "الانتظار المتوقع",
      ja: "待ち時間目安",
      zh: "预计等待",
      es: "Espera est.",
    }),
    tokenStart: t({
      en: "Token 1",
      si: "ටෝකන් 1",
      ta: "டோக்கன் 1",
      hi: "टोकन 1",
      fr: "Jeton 1",
      de: "Token 1",
      ar: "رقم دور 1",
      ja: "トークン 1",
      zh: "号码 1",
      es: "Ficha 1",
    }),
    yourTurn: t({
      en: "Your Turn (Token {myToken})",
      si: "ඔබගේ වාරය (ටෝකන් {myToken})",
      ta: "உங்கள் முறை (டோக்கன் {myToken})",
      hi: "आपकी बारी (टोकन {myToken})",
      fr: "Votre tour (Jeton {myToken})",
      de: "Ihr Zug (Token {myToken})",
      ar: "دورك (الرقم {myToken})",
      ja: "あなたの番 (トークン {myToken})",
      zh: "到您了 (号码 {myToken})",
      es: "Su turno (Ficha {myToken})",
    }),
    patientsAheadText: t({
      en: "patients ahead of you",
      si: "රෝගීන් පෝලිමේ ඔබට ඉදිරියෙන් සිටී",
      ta: "நோயாளிகள் உங்களுக்கு முன்னால் உள்ளனர்",
      hi: "मरीज आपसे आगे हैं",
      fr: "patients devant vous",
      de: "Patienten vor Ihnen",
      ar: "مرضى بانتظار دورهم قبلك",
      ja: "人があなたの前に待っています",
      zh: "位患者在您前面",
      es: "pacientes delante de usted",
    }),
    patientAheadText: t({
      en: "patient ahead of you",
      si: "රෝගියෙකු පෝලිමේ ඔබට ඉදිරියෙන් සිටී",
      ta: "நோயாளி உங்களுக்கு முன்னால் உள்ளார்",
      hi: "मरीज आपसे आगे है",
      fr: "patient devant vous",
      de: "Patient vor Ihnen",
      ar: "مريض بانتظار دوره قبلك",
      ja: "人があなたの前に待っています",
      zh: "位患者在您前面",
      es: "paciente delante de usted",
    }),
    sessionDetails: t({
      en: "Session Details",
      si: "සැසියේ විස්තර",
      ta: "அமர்வு விவரங்கள்",
      hi: "सत्र का विवरण",
      fr: "Détails de la session",
      de: "Sitzungsdetails",
      ar: "تفاصيل الجلسة",
      ja: "セッション詳細",
      zh: "就诊信息",
      es: "Detalles de la sesión",
    }),
    avgTimeText: t({
      en: "Average time per patient: ~15 mins",
      si: "රෝගියෙකු සඳහා සාමාන්‍ය කාලය: විනාඩි ~15",
      ta: "ஒரு நோயாளிக்கான சராசரி நேரம்: ~15 நிமிடங்கள்",
      hi: "प्रति मरीज औसत समय: ~15 मिनट",
      fr: "Temps moyen par patient : ~15 min",
      de: "Durchschnittliche Zeit pro Patient: ~15 Min.",
      ar: "متوسط الوقت لكل مريض: ~١٥ دقيقة",
      ja: "患者1人あたりの平均時間：約15分",
      zh: "平均每位患者诊断时间：约15分钟",
      es: "Tiempo promedio por paciente: ~15 minutos",
    }),
    checkedInTitle: t({
      en: "You're checked in!",
      si: "ඔබ ලියාපදිංචි වී ඇත!",
      ta: "நீங்கள் செக்-இன் செய்துவிட்டீர்கள்!",
      hi: "आपने चेक-इन कर लिया है!",
      fr: "Vous êtes enregistré !",
      de: "Sie haben eingecheckt!",
      ar: "لقد سجلت وصولك!",
      ja: "チェックインしました！",
      zh: "您已签到就诊！",
      es: "¡Ha registrado su llegada!",
    }),
    checkedInDesc: t({
      en: "Please wait in the seating area. Your token will be called shortly.",
      si: "කරුණාකර අසුන් ගන්නා ස්ථානයේ රැඳී සිටින්න. ඔබගේ ටෝකන් අංකය ළඟදීම කැඳවනු ඇත.",
      ta: "காத்திருக்கும் பகுதியில் தயவுசெய்து காத்திருக்கவும். உங்கள் டோக்கன் விரைவில் அழைக்கப்படும்.",
      hi: "कृपया बैठने की जगह में प्रतीक्षा करें। आपके टोकन को जल्द ही बुलाया जाएगा।",
      fr: "Veuillez patienter en salle d'attente. Votre numéro sera appelé sous peu.",
      de: "Bitte warten Sie im Wartebereich. Ihr Token wird in Kürze aufgerufen.",
      ar: "يرجى الانتظار في منطقة الجلوس. سيتم استدعاء رقم دورك قريبًا.",
      ja: "待合室でお待ちください。まもなくお呼び出しいたします。",
      zh: "请在候诊区等候。您的号码很快就会被呼叫。",
      es: "Por favor espere en el área de asientos. Su ficha será llamada en breve.",
    }),
    hospitalQuestion: t({
      en: "Are you at the hospital?",
      si: "ඔබ රෝහලේ සිටීද?",
      ta: "நீங்கள் மருத்துவமனையில் இருக்கிறீர்களா?",
      hi: "क्या आप अस्पताल में हैं?",
      fr: "Êtes-vous à l'hôpital ?",
      de: "Sind Sie im Krankenhaus?",
      ar: "هل أنت في المستشفى؟",
      ja: "病院に到着されていますか？",
      zh: "您已到达医院了吗？",
      es: "¿Está en el hospital?",
    }),
    hospitalQuestionDesc: t({
      en: "Let the doctor know you've arrived so they can call you in.",
      si: "ඔබ පැමිණි බව වෛද්‍යවරයාට දන්වන්න එවිට ඔවුන්ට ඔබව කැඳවිය හැක.",
      ta: "நீங்கள் வந்துவிட்டீர்கள் என்பதை மருத்துவருக்குத் தெரியப்படுத்துங்கள், அப்போதுதான் அவர்கள் உங்களை அழைக்க முடியும்.",
      hi: "डॉक्टर को बताएं कि आप आ गए हैं ताकि वे आपको अंदर बुला सकें।",
      fr: "Informez le médecin de votre arrivée pour qu'il puisse vous appeler.",
      de: "Geben Sie dem Arzt Bescheid, dass Sie da sind, damit er Sie aufrufen kann.",
      ar: "أخبر الطبيب بوصولك حتى يتمكن من استدعائك.",
      ja: "到着を医師に知らせて、呼び出しを可能にします。",
      zh: "通知医生您已到达，以便他们呼叫您就诊。",
      es: "Informe al médico que ha llegado para que puedan llamarlo.",
    }),
    arrivedButton: t({
      en: "I Have Arrived",
      si: "මා පැමිණ ඇත",
      ta: "நான் வந்துவிட்டேன்",
      hi: "मैं आ गया हूँ",
      fr: "Je suis arrivé",
      de: "Ich bin angekommen",
      ar: "لقد وصلت",
      ja: "到着しました",
      zh: "我已到达",
      es: "He llegado",
    }),
  },
} satisfies Dictionary

export default queueTrackerContent
