/* eslint-disable */
export default {
  "key": "dashboard",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "welcomeTitle": "Welcome back",
        "welcomeSubtitle": "Manage your health journey, view upcoming appointments, and keep track of your medical records.",
        "bookAppointment": "Book Appointment",
        "myAppointments": "My Appointments",
        "queueTracker": "Queue Tracker",
        "healthRecords": "Health Records",
        "activeQueue": "Active Queue",
        "tokenLabel": "Token",
        "roomLabel": "Room",
        "estWaitTime": "Est. wait time",
        "mins": "mins",
        "patientsAhead": "patients ahead",
        "viewLiveTracker": "View Live Tracker",
        "upcomingAppointments": "Upcoming Appointments",
        "viewAll": "View all",
        "detailsButton": "Details",
        "notificationsTitle": "Notifications",
        "viewAllNotifications": "View all notifications"
      },
      "si": {
        "welcomeTitle": "නැවත සාදරයෙන් පිළිගනිමු",
        "welcomeSubtitle": "ඔබගේ සෞඛ්‍ය ගමන කළමනාකරණය කරන්න, ඉදිරි හමුවීම් බලන්න, සහ සෞඛ්‍ය වාර්තා නිරීක්ෂණය කරන්න.",
        "bookAppointment": "වේලාවක් වෙන් කරන්න",
        "myAppointments": "මගේ හමුවීම්",
        "queueTracker": "පෝලිම් ට්‍රැකර්",
        "healthRecords": "සෞඛ්‍ය වාර්තා",
        "activeQueue": "ක්‍රියාකාරී පෝලිම",
        "tokenLabel": "ටෝකන් අංකය",
        "roomLabel": "කාමරය",
        "estWaitTime": "ඇස්තමේන්තුගත කාලය",
        "mins": "මිනිත්තු",
        "patientsAhead": "රෝගීන් පෝලිමේ සිටී",
        "viewLiveTracker": "සජීවී ට්‍රැකර් බලන්න",
        "upcomingAppointments": "ඉදිරි හමුවීම්",
        "viewAll": "සියල්ල බලන්න",
        "detailsButton": "විස්තර",
        "notificationsTitle": "දැනුම්දීම්",
        "viewAllNotifications": "සියලුම දැනුම්දීම් බලන්න"
      },
      "ta": {
        "welcomeTitle": "மீண்டும் வருக",
        "welcomeSubtitle": "உங்கள் சுகாதார பயணத்தை நிர்வகிக்கவும், வரவிருக்கும் அப்பாயிண்ட்மெண்ட்களைப் பார்க்கவும் மற்றும் உங்கள் மருத்துவ பதிவுகளைக் கண்காணிக்கவும்.",
        "bookAppointment": "அப்பாயிண்ட்மெண்ட் முன்பதிவு",
        "myAppointments": "என் அப்பாயிண்ட்மெண்ட்கள்",
        "queueTracker": "வரிசை டிராக்கர்",
        "healthRecords": "சுகாதார பதிவுகள்",
        "activeQueue": "செயலில் உள்ள வரிசை",
        "tokenLabel": "டோக்கன்",
        "roomLabel": "அறை",
        "estWaitTime": "மதிப்பிடப்பட்ட காத்திருப்பு நேரம்",
        "mins": "நிமிடங்கள்",
        "patientsAhead": "நோயாளிகள் முன்னால் உள்ளனர்",
        "viewLiveTracker": "நேரடி டிராக்கரைப் பார்க்கவும்",
        "upcomingAppointments": "வரவிருக்கும் அப்பாயிண்ட்மெண்ட்கள்",
        "viewAll": "அனைத்தையும் காட்டு",
        "detailsButton": "விவரங்கள்",
        "notificationsTitle": "அறிவிப்புகள்",
        "viewAllNotifications": "அனைத்து அறிவிப்புகளையும் பார்க்கவும்"
      },
      "hi": {
        "welcomeTitle": "स्वागत हे",
        "welcomeSubtitle": "अपनी स्वास्थ्य यात्रा प्रबंधित करें, आगामी अपॉइंटमेंट देखें, और अपने मेडिकल रिकॉर्ड पर नज़र रखें।",
        "bookAppointment": "अपॉइंटमेंट बुक करें",
        "myAppointments": "मेरे अपॉइंटमेंट",
        "queueTracker": "कतार ट्रैकर",
        "healthRecords": "स्वास्थ्य रिकॉर्ड",
        "activeQueue": "सक्रिय कतार",
        "tokenLabel": "टोकन",
        "roomLabel": "कमरा",
        "estWaitTime": "अनुमानित प्रतीक्षा समय",
        "mins": "मिनट",
        "patientsAhead": "मरीज आगे हैं",
        "viewLiveTracker": "लाइव ट्रैकर देखें",
        "upcomingAppointments": "आगामी अपॉइंटमेंट",
        "viewAll": "सभी देखें",
        "detailsButton": "विवरण",
        "notificationsTitle": "सूचनाएं",
        "viewAllNotifications": "सभी सूचनाएं देखें"
      },
      "fr": {
        "welcomeTitle": "Bon retour",
        "welcomeSubtitle": "Gérez votre parcours de santé, affichez les rendez-vous à venir et suivez vos dossiers médicaux.",
        "bookAppointment": "Prendre RDV",
        "myAppointments": "Mes rendez-vous",
        "queueTracker": "Suivi de file",
        "healthRecords": "Dossiers de santé",
        "activeQueue": "File active",
        "tokenLabel": "Jeton",
        "roomLabel": "Salle",
        "estWaitTime": "Attente est.",
        "mins": "min",
        "patientsAhead": "patients devant",
        "viewLiveTracker": "Voir le suivi en direct",
        "upcomingAppointments": "Rendez-vous à venir",
        "viewAll": "Voir tout",
        "detailsButton": "Détails",
        "notificationsTitle": "Notifications",
        "viewAllNotifications": "Voir toutes les notifications"
      },
      "de": {
        "welcomeTitle": "Willkommen zurück",
        "welcomeSubtitle": "Verwalten Sie Ihre Gesundheitsreise, sehen Sie anstehende Termine ein und behalten Sie Ihre Krankenakten im Auge.",
        "bookAppointment": "Termin buchen",
        "myAppointments": "Meine Termine",
        "queueTracker": "Warteschlangen-Tracker",
        "healthRecords": "Gesundheitsakten",
        "activeQueue": "Aktive Warteschlange",
        "tokenLabel": "Token",
        "roomLabel": "Raum",
        "estWaitTime": "Geschätzte Wartezeit",
        "mins": "Min.",
        "patientsAhead": "Patienten vor Ihnen",
        "viewLiveTracker": "Live-Tracker anzeigen",
        "upcomingAppointments": "Anstehende Termine",
        "viewAll": "Alle anzeigen",
        "detailsButton": "Details",
        "notificationsTitle": "Benachrichtigungen",
        "viewAllNotifications": "Alle Benachrichtigungen anzeigen"
      },
      "ar": {
        "welcomeTitle": "مرحبًا بعودتك",
        "welcomeSubtitle": "إدارة رحلتك الصحية، وعرض المواعيد القادمة، ومتابعة سجلاتك الطبية.",
        "bookAppointment": "حجز موعد",
        "myAppointments": "مواعيدي",
        "queueTracker": "متبع الطابور",
        "healthRecords": "السجلات الصحية",
        "activeQueue": "الطابور النشط",
        "tokenLabel": "الرقم",
        "roomLabel": "غرفة",
        "estWaitTime": "وقت الانتظار المتوقع",
        "mins": "دقائق",
        "patientsAhead": "مرضى بانتظار دورهم",
        "viewLiveTracker": "عرض التتبع المباشر",
        "upcomingAppointments": "المواعيد القادمة",
        "viewAll": "عرض الكل",
        "detailsButton": "التفاصيل",
        "notificationsTitle": "الإشعارات",
        "viewAllNotifications": "عرض جميع الإشعارات"
      },
      "ja": {
        "welcomeTitle": "おかえりなさい",
        "welcomeSubtitle": "健康管理、今後の予約確認、医療記録の追跡などを行います。",
        "bookAppointment": "予約する",
        "myAppointments": "マイ予約",
        "queueTracker": "待ち順トラッカー",
        "healthRecords": "健康記録",
        "activeQueue": "進行中の待ち順",
        "tokenLabel": "トークン",
        "roomLabel": "部屋",
        "estWaitTime": "待ち時間目安",
        "mins": "分",
        "patientsAhead": "人の待ち順",
        "viewLiveTracker": "ライブ追跡を表示",
        "upcomingAppointments": "今後の予定",
        "viewAll": "すべて表示",
        "detailsButton": "詳細",
        "notificationsTitle": "通知",
        "viewAllNotifications": "すべての通知を表示"
      },
      "zh": {
        "welcomeTitle": "欢迎回来",
        "welcomeSubtitle": "管理您的健康旅程，查看即将到来的预约，并记录您的医疗档案。",
        "bookAppointment": "预约挂号",
        "myAppointments": "我的预约",
        "queueTracker": "排队追踪",
        "healthRecords": "健康档案",
        "activeQueue": "当前排队",
        "tokenLabel": "号码",
        "roomLabel": "诊室",
        "estWaitTime": "预计等待时间",
        "mins": "分钟",
        "patientsAhead": "名患者排在前面",
        "viewLiveTracker": "查看实时排队",
        "upcomingAppointments": "即将到来的预约",
        "viewAll": "查看全部",
        "detailsButton": "详情",
        "notificationsTitle": "通知",
        "viewAllNotifications": "查看全部通知"
      },
      "es": {
        "welcomeTitle": "Bienvenido de nuevo",
        "welcomeSubtitle": "Gestione su viaje de salud, vea sus próximas citas y realice un seguimiento de sus registros médicos.",
        "bookAppointment": "Reservar cita",
        "myAppointments": "Mis citas",
        "queueTracker": "Seguimiento de cola",
        "healthRecords": "Registros de salud",
        "activeQueue": "Cola activa",
        "tokenLabel": "Ficha",
        "roomLabel": "Consultorio",
        "estWaitTime": "Tiempo de espera est.",
        "mins": "mins",
        "patientsAhead": "pacientes adelante",
        "viewLiveTracker": "Ver seguimiento en vivo",
        "upcomingAppointments": "Próximas citas",
        "viewAll": "Ver todo",
        "detailsButton": "Detalles",
        "notificationsTitle": "Notificaciones",
        "viewAllNotifications": "Ver todas las notificaciones"
      }
    }
  },
  "localIds": [
    "dashboard::local::src\\pages\\patient\\Dashboard.content.ts"
  ]
} as const;
