/* eslint-disable */
export default {
  "key": "queue-tracker",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "title": "Live Queue Tracker",
        "subtitle": "Track your appointment in real-time",
        "sessionActive": "Session In Progress",
        "sessionInactive": "Session Not Started",
        "currentlyCalling": "Currently Calling",
        "yourToken": "Your Token",
        "estWait": "Est. Wait",
        "tokenStart": "Token 1",
        "yourTurn": "Your Turn (Token {myToken})",
        "patientsAheadText": "patients ahead of you",
        "patientAheadText": "patient ahead of you",
        "sessionDetails": "Session Details",
        "avgTimeText": "Average time per patient: ~15 mins",
        "checkedInTitle": "You're checked in!",
        "checkedInDesc": "Please wait in the seating area. Your token will be called shortly.",
        "hospitalQuestion": "Are you at the hospital?",
        "hospitalQuestionDesc": "Let the doctor know you've arrived so they can call you in.",
        "arrivedButton": "I Have Arrived"
      },
      "si": {
        "title": "සජීවී පෝලිම් ට්‍රැකර්",
        "subtitle": "ඔබගේ හමුවීම සජීවීව නිරීක්ෂණය කරන්න",
        "sessionActive": "සැසිය ක්‍රියාත්මක වෙමින් පවතී",
        "sessionInactive": "සැසිය තවමත් ආරම්භ කර නොමැත",
        "currentlyCalling": "දැනට කැඳවන අංකය",
        "yourToken": "ඔබගේ ටෝකන් අංකය",
        "estWait": "ඇස්තමේන්තුගත කාලය",
        "tokenStart": "ටෝකන් 1",
        "yourTurn": "ඔබගේ වාරය (ටෝකන් {myToken})",
        "patientsAheadText": "රෝගීන් පෝලිමේ ඔබට ඉදිරියෙන් සිටී",
        "patientAheadText": "රෝගියෙකු පෝලිමේ ඔබට ඉදිරියෙන් සිටී",
        "sessionDetails": "සැසියේ විස්තර",
        "avgTimeText": "රෝගියෙකු සඳහා සාමාන්‍ය කාලය: විනාඩි ~15",
        "checkedInTitle": "ඔබ ලියාපදිංචි වී ඇත!",
        "checkedInDesc": "කරුණාකර අසුන් ගන්නා ස්ථානයේ රැඳී සිටින්න. ඔබගේ ටෝකන් අංකය ළඟදීම කැඳවනු ඇත.",
        "hospitalQuestion": "ඔබ රෝහලේ සිටීද?",
        "hospitalQuestionDesc": "ඔබ පැමිණි බව වෛද්‍යවරයාට දන්වන්න එවිට ඔවුන්ට ඔබව කැඳවිය හැක.",
        "arrivedButton": "මා පැමිණ ඇත"
      },
      "ta": {
        "title": "நேரடி வரிசை டிராக்கர்",
        "subtitle": "உங்கள் அப்பாயிண்ட்மெண்ட்டை நிகழ்நேரத்தில் கண்காணிக்கவும்",
        "sessionActive": "அமர்வு செயல்பாட்டில் உள்ளது",
        "sessionInactive": "அமர்வு தொடங்கவில்லை",
        "currentlyCalling": "தற்போது அழைக்கப்படுகிறது",
        "yourToken": "உங்கள் டோக்கன்",
        "estWait": "மதிப்பிடப்பட்ட காத்திருப்பு",
        "tokenStart": "டோக்கன் 1",
        "yourTurn": "உங்கள் முறை (டோக்கன் {myToken})",
        "patientsAheadText": "நோயாளிகள் உங்களுக்கு முன்னால் உள்ளனர்",
        "patientAheadText": "நோயாளி உங்களுக்கு முன்னால் உள்ளார்",
        "sessionDetails": "அமர்வு விவரங்கள்",
        "avgTimeText": "ஒரு நோயாளிக்கான சராசரி நேரம்: ~15 நிமிடங்கள்",
        "checkedInTitle": "நீங்கள் செக்-இன் செய்துவிட்டீர்கள்!",
        "checkedInDesc": "காத்திருக்கும் பகுதியில் தயவுசெய்து காத்திருக்கவும். உங்கள் டோக்கன் விரைவில் அழைக்கப்படும்.",
        "hospitalQuestion": "நீங்கள் மருத்துவமனையில் இருக்கிறீர்களா?",
        "hospitalQuestionDesc": "நீங்கள் வந்துவிட்டீர்கள் என்பதை மருத்துவருக்குத் தெரியப்படுத்துங்கள், அப்போதுதான் அவர்கள் உங்களை அழைக்க முடியும்.",
        "arrivedButton": "நான் வந்துவிட்டேன்"
      },
      "hi": {
        "title": "लाइव कतार ट्रैकर",
        "subtitle": "वास्तविक समय में अपने अपॉइंटमेंट को ट्रैक करें",
        "sessionActive": "सत्र प्रगति पर है",
        "sessionInactive": "सत्र शुरू नहीं हुआ",
        "currentlyCalling": "वर्तमान में बुला रहे हैं",
        "yourToken": "आपका टोकन",
        "estWait": "अनुमानित प्रतीक्षा",
        "tokenStart": "टोकन 1",
        "yourTurn": "आपकी बारी (टोकन {myToken})",
        "patientsAheadText": "मरीज आपसे आगे हैं",
        "patientAheadText": "मरीज आपसे आगे है",
        "sessionDetails": "सत्र का विवरण",
        "avgTimeText": "प्रति मरीज औसत समय: ~15 मिनट",
        "checkedInTitle": "आपने चेक-इन कर लिया है!",
        "checkedInDesc": "कृपया बैठने की जगह में प्रतीक्षा करें। आपके टोकन को जल्द ही बुलाया जाएगा।",
        "hospitalQuestion": "क्या आप अस्पताल में हैं?",
        "hospitalQuestionDesc": "डॉक्टर को बताएं कि आप आ गए हैं ताकि वे आपको अंदर बुला सकें।",
        "arrivedButton": "मैं आ गया हूँ"
      },
      "fr": {
        "title": "Suivi de file en direct",
        "subtitle": "Suivez votre rendez-vous en temps réel",
        "sessionActive": "Session en cours",
        "sessionInactive": "Session non commencée",
        "currentlyCalling": "Appel en cours",
        "yourToken": "Votre jeton",
        "estWait": "Attente est.",
        "tokenStart": "Jeton 1",
        "yourTurn": "Votre tour (Jeton {myToken})",
        "patientsAheadText": "patients devant vous",
        "patientAheadText": "patient devant vous",
        "sessionDetails": "Détails de la session",
        "avgTimeText": "Temps moyen par patient : ~15 min",
        "checkedInTitle": "Vous êtes enregistré !",
        "checkedInDesc": "Veuillez patienter en salle d'attente. Votre numéro sera appelé sous peu.",
        "hospitalQuestion": "Êtes-vous à l'hôpital ?",
        "hospitalQuestionDesc": "Informez le médecin de votre arrivée pour qu'il puisse vous appeler.",
        "arrivedButton": "Je suis arrivé"
      },
      "de": {
        "title": "Live-Warteschlangen-Tracker",
        "subtitle": "Verfolgen Sie Ihren Termin in Echtzeit",
        "sessionActive": "Sitzung läuft",
        "sessionInactive": "Sitzung nicht gestartet",
        "currentlyCalling": "Aktueller Aufruf",
        "yourToken": "Ihr Token",
        "estWait": "Geschätzte Wartezeit",
        "tokenStart": "Token 1",
        "yourTurn": "Ihr Zug (Token {myToken})",
        "patientsAheadText": "Patienten vor Ihnen",
        "patientAheadText": "Patient vor Ihnen",
        "sessionDetails": "Sitzungsdetails",
        "avgTimeText": "Durchschnittliche Zeit pro Patient: ~15 Min.",
        "checkedInTitle": "Sie haben eingecheckt!",
        "checkedInDesc": "Bitte warten Sie im Wartebereich. Ihr Token wird in Kürze aufgerufen.",
        "hospitalQuestion": "Sind Sie im Krankenhaus?",
        "hospitalQuestionDesc": "Geben Sie dem Arzt Bescheid, dass Sie da sind, damit er Sie aufrufen kann.",
        "arrivedButton": "Ich bin angekommen"
      },
      "ar": {
        "title": "متبع الطابور المباشر",
        "subtitle": "تتبع موعدك في الوقت الحقيقي",
        "sessionActive": "الجلسة جارية",
        "sessionInactive": "لم تبدأ الجلسة بعد",
        "currentlyCalling": "يتم استدعاؤه حاليًا",
        "yourToken": "رقم دورك",
        "estWait": "الانتظار المتوقع",
        "tokenStart": "رقم دور 1",
        "yourTurn": "دورك (الرقم {myToken})",
        "patientsAheadText": "مرضى بانتظار دورهم قبلك",
        "patientAheadText": "مريض بانتظار دوره قبلك",
        "sessionDetails": "تفاصيل الجلسة",
        "avgTimeText": "متوسط الوقت لكل مريض: ~١٥ دقيقة",
        "checkedInTitle": "لقد سجلت وصولك!",
        "checkedInDesc": "يرجى الانتظار في منطقة الجلوس. سيتم استدعاء رقم دورك قريبًا.",
        "hospitalQuestion": "هل أنت في المستشفى؟",
        "hospitalQuestionDesc": "أخبر الطبيب بوصولك حتى يتمكن من استدعائك.",
        "arrivedButton": "لقد وصلت"
      },
      "ja": {
        "title": "ライブ待ち順トラッカー",
        "subtitle": "予約状況をリアルタイムで確認",
        "sessionActive": "セッション進行中",
        "sessionInactive": "セッション開始前",
        "currentlyCalling": "現在お呼び出し中",
        "yourToken": "あなたのトークン",
        "estWait": "待ち時間目安",
        "tokenStart": "トークン 1",
        "yourTurn": "あなたの番 (トークン {myToken})",
        "patientsAheadText": "人があなたの前に待っています",
        "patientAheadText": "人があなたの前に待っています",
        "sessionDetails": "セッション詳細",
        "avgTimeText": "患者1人あたりの平均時間：約15分",
        "checkedInTitle": "チェックインしました！",
        "checkedInDesc": "待合室でお待ちください。まもなくお呼び出しいたします。",
        "hospitalQuestion": "病院に到着されていますか？",
        "hospitalQuestionDesc": "到着を医師に知らせて、呼び出しを可能にします。",
        "arrivedButton": "到着しました"
      },
      "zh": {
        "title": "实时排队追踪",
        "subtitle": "实时追踪您的预约进度",
        "sessionActive": "就诊进行中",
        "sessionInactive": "就诊未开始",
        "currentlyCalling": "当前呼叫",
        "yourToken": "您的号码",
        "estWait": "预计等待",
        "tokenStart": "号码 1",
        "yourTurn": "到您了 (号码 {myToken})",
        "patientsAheadText": "位患者在您前面",
        "patientAheadText": "位患者在您前面",
        "sessionDetails": "就诊信息",
        "avgTimeText": "平均每位患者诊断时间：约15分钟",
        "checkedInTitle": "您已签到就诊！",
        "checkedInDesc": "请在候诊区等候。您的号码很快就会被呼叫。",
        "hospitalQuestion": "您已到达医院了吗？",
        "hospitalQuestionDesc": "通知医生您已到达，以便他们呼叫您就诊。",
        "arrivedButton": "我已到达"
      },
      "es": {
        "title": "Seguimiento de cola en vivo",
        "subtitle": "Siga su cita en tiempo real",
        "sessionActive": "Sesión en progreso",
        "sessionInactive": "Sesión no iniciada",
        "currentlyCalling": "Llamando actualmente",
        "yourToken": "Su ficha",
        "estWait": "Espera est.",
        "tokenStart": "Ficha 1",
        "yourTurn": "Su turno (Ficha {myToken})",
        "patientsAheadText": "pacientes delante de usted",
        "patientAheadText": "paciente delante de usted",
        "sessionDetails": "Detalles de la sesión",
        "avgTimeText": "Tiempo promedio por paciente: ~15 minutos",
        "checkedInTitle": "¡Ha registrado su llegada!",
        "checkedInDesc": "Por favor espere en el área de asientos. Su ficha será llamada en breve.",
        "hospitalQuestion": "¿Está en el hospital?",
        "hospitalQuestionDesc": "Informe al médico que ha llegado para que puedan llamarlo.",
        "arrivedButton": "He llegado"
      }
    }
  },
  "localIds": [
    "queue-tracker::local::src\\pages\\patient\\QueueTracker.content.ts"
  ]
} as const;
