import { t, type Dictionary } from "intlayer"

const patientLayoutContent = {
  key: "patient-layout",
  content: {
    dashboard: t({
      en: "Dashboard",
      si: "පාලක පුවරුව",
      ta: "டாஷ்போர்டு",
      hi: "डैशबोर्ड",
      fr: "Tableau de bord",
      de: "Dashboard",
      ar: "لوحة التحكم",
      ja: "控制台", // Japanese: "ダッシュボード" or "コントロールパネル"
      zh: "控制台",
      es: "Panel de control",
    }),
    bookAppointment: t({
      en: "Book Appointment",
      si: "වේලාවක් වෙන් කරන්න",
      ta: "அப்பாயிண்ட்மெண்ட் முன்பதிவு",
      hi: "अपॉइंटमेंट बुक करें",
      fr: "Prendre RDV",
      de: "Termin buchen",
      ar: "حجز موعد",
      ja: "予約する",
      zh: "预约挂号",
      es: "Reservar cita",
    }),
    myAppointments: t({
      en: "My Appointments",
      si: "මගේ හමුවීම්",
      ta: "என் அப்பாயிண்ட்மெண்ட்கள்",
      hi: "मेरे अपॉइंटमेंट",
      fr: "Mes rendez-vous",
      de: "Meine Termine",
      ar: "مواعيدي",
      ja: "マイ予約",
      zh: "我的预约",
      es: "Mis citas",
    }),
    queueTracker: t({
      en: "Queue Tracker",
      si: "පෝලිම් ට්‍රැකර්",
      ta: "வரிசை டிராக்கர்",
      hi: "कतार ट्रैकर",
      fr: "Suivi de file",
      de: "Warteschlangen-Tracker",
      ar: "متبع الطابور",
      ja: "待ち順トラッカー",
      zh: "排队追踪",
      es: "Seguimiento de cola",
    }),
    documents: t({
      en: "Documents",
      si: "ලේඛන",
      ta: "ஆவணங்கள்",
      hi: "दस्तावेज़",
      fr: "Documents",
      de: "Dokumente",
      ar: "المستندات",
      ja: "書類",
      zh: "我的文件",
      es: "Documentos",
    }),
    healthRecord: t({
      en: "Health Record",
      si: "සෞඛ්‍ය වාර්තාව",
      ta: "சுகாதார பதிவு",
      hi: "स्वास्थ्य रिकॉर्ड",
      fr: "Dossier médical",
      de: "Krankenakte",
      ar: "السجل الصحي",
      ja: "健康記録",
      zh: "健康记录",
      es: "Registro de salud",
    }),
    notifications: t({
      en: "Notifications",
      si: "දැනුම්දීම්",
      ta: "அறிவிப்புகள்",
      hi: "सूचनाएं",
      fr: "Notifications",
      de: "Benachrichtigungen",
      ar: "الإشعارات",
      ja: "通知",
      zh: "通知",
      es: "Notificaciones",
    }),
    settings: t({
      en: "Settings",
      si: "සැකසුම්",
      ta: "அமைப்புகள்",
      hi: "सेटिंग्स",
      fr: "Paramètres",
      de: "Einstellungen",
      ar: "الإعدادات",
      ja: "設定",
      zh: "设置",
      es: "Configuración",
    }),
    signOut: t({
      en: "Sign Out",
      si: "නික්ම යන්න",
      ta: "வெளியேறு",
      hi: "साइन आउट",
      fr: "Déconnexion",
      de: "Abmelden",
      ar: "تسجيل الخروج",
      ja: "サインアウト",
      zh: "退出登录",
      es: "Cerrar sesión",
    }),
    viewNotifications: t({
      en: "View notifications",
      si: "දැනුම්දීම් බලන්න",
      ta: "அறிவிப்புகளைப் பார்க்கவும்",
      hi: "सूचनाएं देखें",
      fr: "Voir les notifications",
      de: "Benachrichtigungen anzeigen",
      ar: "عرض الإشعارات",
      ja: "通知を表示",
      zh: "查看通知",
      es: "Ver notificaciones",
    }),
  },
} satisfies Dictionary

export default patientLayoutContent
